### Pokeman

In [1]:
# Data manipulation
import pandas as pd
import numpy as np

# Visualisation libraries
import matplotlib.pyplot as plt
import seaborn as sns

#Ignoring warnings
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv("../DataSets/Pokemon Database.csv")

In [4]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1382 entries, 0 to 1381
Data columns (total 45 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Pokemon Id                         1382 non-null   int64
 1   Pokedex Number                     1382 non-null   int64
 2   Pokemon Name                       1382 non-null   object
 3   Classification                     1382 non-null   object
 4   Alternate Form Name                328 non-null    object
 5   Original Pokemon ID                328 non-null    float64
 6   Legendary Type                     157 non-null    object
 7   Pokemon Height                     1382 non-null   float64
 8   Pokemon Weight                     1382 non-null   float64
 9   Primary Type                       1382 non-null   object
 10  Secondary Type                     752 non-null    object
 11  Primary Ability                    1382 non-null   object
 12  Primary Ability Description        1382 non-null   object
 13  Secondary Ability                  652 non-null    object
 14  Secondary Ability Description      652 non-null    object
 15  Hidden Ability                     1044 non-null   object
 16  Hidden Ability Description         1044 non-null   object
 17  Special Event Ability              2 non-null      object
 18  Special Event Ability Description  2 non-null      object
 19  Male Ratio                         1382 non-null   float64
 20  Female Ratio                       1382 non-null   float64
 21  Base Happiness                     1382 non-null   int64
 22  Game(s) of Origin                  1382 non-null   object
 23  Health Stat                        1382 non-null   int64
 24  Attack Stat                        1382 non-null   int64
 25  Defense Stat                       1382 non-null   int64
 26  Special Attack Stat                1382 non-null   int64
 27  Special Defense Stat               1382 non-null   int64
 28  Speed Stat                         1382 non-null   int64
 29  Base Stat Total                    1382 non-null   int64
 30  Health EV                          1382 non-null   int64
 31  Attack EV                          1382 non-null   int64
 32  Defense EV                         1382 non-null   int64
 33  Special Attack EV                  1382 non-null   int64
 34  Special Defense EV                 1382 non-null   int64
 35  Speed EV                           1382 non-null   int64
 36  EV Yield Total                     1382 non-null   int64
 37  Catch Rate                         1382 non-null   int64
 38  Experience Growth                  1382 non-null   object
 39  Experience Growth Total            1382 non-null   int64
 40  Primary Egg Group                  1382 non-null   object
 41  Secondary Egg Group                347 non-null    object
 42  Egg Cycle Count                    1382 non-null   int64
 43  Pre-Evolution Pokemon Id           608 non-null    float64
 44  Evolution Details                  571 non-null    object
dtypes: float64(6), int64(20), object(19)
memory usage: 486.0+ KB

### Numerical Analysis

In [6]:
numerical_cols = df.select_dtypes("number")
numerical_cols

,Pokemon Id,Pokedex Number,Original Pokemon ID,Pokemon Height,Pokemon Weight,Male Ratio,Female Ratio,Base Happiness,Health Stat,Attack Stat,...,Attack EV,Defense EV,Special Attack EV,Special Defense EV,Speed EV,EV Yield Total,Catch Rate,Experience Growth Total,Egg Cycle Count,Pre-Evolution Pokemon Id
0,1,1,NaN,0.7,6.9,87.5,12.5,50,45,49,...,0,0,1,0,0,1,45,1059860,20,NaN
1,2,2,NaN,1.0,13.0,87.5,12.5,50,60,62,...,0,0,1,1,0,2,45,1059860,20,1.0
2,3,3,NaN,2.0,100.0,87.5,12.5,50,80,82,...,0,0,2,1,0,3,45,1059860,20,2.0
3,4,3,3.0,2.4,155.5,87.5,12.5,70,80,100,...,0,0,2,1,0,3,45,1059860,20,NaN
4,1526,3,3.0,24.0,0.0,87.5,12.5,50,80,82,...,0,0,2,1,0,3,45,1059860,20,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1377,1873,1023,NaN,1.6,156.0,0.0,0.0,0,90,72,...,0,0,3,0,0,3,10,1250000,50,NaN
1378,1882,1024,1769.0,1.7,77.0,0.0,0.0,0,160,105,...,0,0,0,0,0,3,255,1250000,0,NaN
1379,1769,1024,NaN,0.2,6.5,0.0,0.0,0,90,65,...,0,1,0,0,0,1,255,1250000,0,NaN
1380,1770,1024,1769.0,0.3,16.0,0.0,0.0,0,95,95,...,0,2,0,2,0,4,255,1250000,0,NaN
1381,1884,1025,NaN,0.3,0.3,0.0,0.0,0,88,88,...,0,3,0,0,0,3,3,1250000,0,NaN

In [7]:
df[numerical_cols.columns].describe()

,Pokemon Id,Pokedex Number,Original Pokemon ID,Pokemon Height,Pokemon Weight,Male Ratio,Female Ratio,Base Happiness,Health Stat,Attack Stat,...,Attack EV,Defense EV,Special Attack EV,Special Defense EV,Speed EV,EV Yield Total,Catch Rate,Experience Growth Total,Egg Cycle Count,Pre-Evolution Pokemon Id
count,1382.000000,1382.00000,328.000000,1382.000000,1382.000000,1382.000000,1382.000000,1382.000000,1382.000000,1382.000000,...,1382.000000,1382.000000,1382.000000,1382.000000,1382.000000,1382.000000,1382.000000,1.382000e+03,1382.000000,608.000000
mean,1026.651954,506.20767,823.338415,1.988495,68.316353,44.328871,37.870839,47.272069,71.506512,80.960926,...,0.539797,0.247467,0.424747,0.225760,0.318379,1.976122,93.745297,1.059808e+06,30.864689,859.848684
std,574.699143,299.02744,521.455495,5.282591,126.529616,28.610044,26.523509,20.092395,26.480814,31.369489,...,0.931122,0.646590,0.868498,0.642206,0.704754,0.757398,75.734484,1.531328e+05,28.693386,545.418302
min,1.000000,1.00000,3.000000,0.100000,0.000000,0.000000,0.000000,0.000000,1.000000,5.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,3.000000,6.000000e+05,0.000000,1.000000
25%,471.250000,229.25000,325.000000,0.500000,7.425000,25.000000,12.500000,50.000000,54.000000,58.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,45.000000,1.000000e+06,20.000000,361.500000
50%,1092.500000,514.50000,944.500000,1.000000,27.550000,50.000000,50.000000,50.000000,70.000000,79.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,60.000000,1.000000e+06,20.000000,905.500000
75%,1536.750000,761.75000,1267.000000,1.600000,69.800000,50.000000,50.000000,50.000000,85.000000,100.000000,...,1.000000,0.000000,0.000000,0.000000,0.000000,3.000000,135.000000,1.250000e+06,25.000000,1319.250000
max,1886.000000,1025.00000,1875.000000,100.000000,999.900000,100.000000,100.000000,140.000000,255.000000,190.000000,...,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,255.000000,1.640000e+06,120.000000,1877.000000

In [5]:
df[['Primary Type', 'Secondary Type']].value_counts(normalize=True) * 100

Primary Type  Secondary Type
"Bug"         "Flying"          4.787234
"Normal"      "Flying"          4.122340
"Grass"       "Poison"          2.127660
"Bug"         "Poison"          1.595745
"Rock"        "Flying"          1.595745
                                  ...
"Poison"      "Bug"             0.132979
"Normal"      "Water"           0.132979
"Poison"      "Ghost"           0.132979
"Steel"       "Fighting"        0.132979
"Water"       "Steel"           0.132979
Name: proportion, Length: 203, dtype: float64

### Categorical Analysis

In [9]:
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
categorical_cols
len(categorical_cols)

19